# Generated by Django 3.0.8 on 2020-07-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('SW', 'Sport wear'), ('S', 'Shirt'), ('OW', 'Outwear')], default='S', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('W', 'warning'), ('S', 'secondary'), ('P', 'primary'), ('D', 'danger')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
