# Generated by Django 3.0.8 on 2020-07-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0005_auto_20200707_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('OW', 'Outwear'), ('S', 'Shirt'), ('SW', 'Sport wear')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('W', 'warning'), ('D', 'danger'), ('S', 'secondary')], max_length=1),
        ),
    ]
