# Generated by Django 3.0.8 on 2020-07-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0009_auto_20200707_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('OW', 'Outwear'), ('SW', 'Sport wear'), ('S', 'Shirt')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('S', 'secondary'), ('P', 'primary'), ('W', 'warning'), ('D', 'danger')], max_length=1),
        ),
    ]
